ls:
  .dir: kebab-case | camelCase | PascalCase
  .js: kebab-case | camelCase | PascalCase
  .jsx: kebab-case | camelCase | PascalCase  
  .ts: kebab-case | camelCase | PascalCase
  .tsx: kebab-case | camelCase | PascalCase
  .vue: kebab-case | camelCase | PascalCase
  .css: kebab-case
  .scss: kebab-case
  .sass: kebab-case
  .less: kebab-case
  .json: kebab-case | camelCase

ignore:
  - node_modules
  - dist
  - build
  - coverage
  - .git
  - .vscode
  - .idea
  - "*.log"
  - ".env*"